### ISSUE TITLE
Comments after no-argument instructions aren't correctly highlighted 

### ISSUE THREAD

**Issue by nitro2k01** [ISSOtm/sublime-RGBDS#1]
As per title and screenshot.

![Screenshot_20200710_050053](https://user-images.githubusercontent.com/10664/87111901-cbd0c480-c26a-11ea-844a-8163937b0d70.png)

**Comment by nitro2k01** [comment]
It appears to only affect instructions written in lower-case.

**Comment by ISSOtm** [comment]
Known bug, fixed in the new version I'm currently testing locally. My plan is to release it once I don't find any bugs for a week.
![Screenshot of that v2.](https://user-images.githubusercontent.com/15271137/87166591-18002100-c2cc-11ea-8459-d0f776a38193.png)

**Comment by ISSOtm** [comment]
Well, fixed since then...
